/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef RTI_CONNEXT_SYSTEMS_SHAPES_BAKE_CONFIG_H
#define RTI_CONNEXT_SYSTEMS_SHAPES_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <reflecs>
#include <reflecs.components.transform>

/* Headers of private dependencies */
#ifdef RTI_CONNEXT_SYSTEMS_SHAPES_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if RTI_CONNEXT_SYSTEMS_SHAPES_IMPL && defined _MSC_VER
#define RTI_CONNEXT_SYSTEMS_SHAPES_EXPORT __declspec(dllexport)
#elif RTI_CONNEXT_SYSTEMS_SHAPES_IMPL
#define RTI_CONNEXT_SYSTEMS_SHAPES_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define RTI_CONNEXT_SYSTEMS_SHAPES_EXPORT __declspec(dllimport)
#else
#define RTI_CONNEXT_SYSTEMS_SHAPES_EXPORT
#endif

#endif

